import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useParams } from "@/lib/router";
import { newsletterApi } from "../../api/newsletter";
import { queryKeys } from "../../lib/queryKeys";

export function OrientLandingPage() {
  const { companyPrefix } = useParams<{ companyPrefix: string }>();
  const [email, setEmail] = useState('');
  const [fullName, setFullName] = useState('');
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const query = useQuery({ queryKey: companyPrefix ? queryKeys.newsletter.landing(companyPrefix) : ['newsletter','landing','none'], queryFn: () => newsletterApi.landingInfo(companyPrefix!), enabled: Boolean(companyPrefix) });
  const subscribe = useMutation({ mutationFn: () => newsletterApi.subscribe(companyPrefix!, { email, fullName: fullName || null }), onSuccess: ()=>{ setError(null); setMessage('You are on the list. Continue to checkout to activate your subscription.'); }, onError:(e)=>setError(e instanceof Error ? e.message : 'Failed to subscribe') });
  const checkout = useMutation({ mutationFn: () => newsletterApi.checkout(companyPrefix!, { email, fullName: fullName || null }), onSuccess:(result:any)=>{ window.location.href = result.checkoutUrl; }, onError:(e)=>setError(e instanceof Error ? e.message : 'Failed to start checkout') });
  const checkoutState = useMemo(() => new URLSearchParams(window.location.search).get('checkout'), []);
  useEffect(() => { document.title = `${query.data?.productName ?? 'Orient Weekly'} · Paperclip`; }, [query.data?.productName]);
  if (!companyPrefix) return null;
  if (query.isLoading) return <div className="p-8 text-sm text-muted-foreground">Loading landing page...</div>;
  const landing:any = query.data ?? {};
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top,#fef3c7,transparent_35%),linear-gradient(180deg,#fffdf7_0%,#fff_45%,#f8fafc_100%)] text-slate-900"><main className="mx-auto flex min-h-screen max-w-6xl flex-col justify-center px-6 py-12 lg:px-10"><div className="grid gap-10 lg:grid-cols-[1.2fr,0.8fr] lg:items-center"><section className="space-y-6"><div className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-white/80 px-3 py-1 text-xs font-medium text-amber-800 shadow-sm">{landing.productName}</div><div className="space-y-4"><h1 className="max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">Clear weekly signal for people building in public.</h1><p className="max-w-2xl text-lg text-slate-600">{landing.description}</p></div></section><section className="rounded-3xl border border-slate-200 bg-white/90 p-6 shadow-xl shadow-amber-100/30 backdrop-blur"><div className="mb-5 flex items-center justify-between gap-3"><div><div className="text-sm font-medium text-slate-500">Subscribe</div><div className="mt-1 text-2xl font-semibold">Start with the first issue</div></div><div className="rounded-full bg-slate-900 px-3 py-1 text-xs font-medium text-white">{landing.priceLabel}</div></div><div className="space-y-3"><input value={fullName} onChange={(e)=>setFullName(e.target.value)} placeholder="Full name" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" /><input value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm" /></div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><button onClick={()=>subscribe.mutate()} disabled={!email.trim() || subscribe.isPending || checkout.isPending} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-medium text-white disabled:opacity-60">Join the list</button><button onClick={()=>checkout.mutate()} disabled={!email.trim() || subscribe.isPending || checkout.isPending} className="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-medium text-slate-900 disabled:opacity-60">Continue to checkout</button></div>{checkoutState==='success' && <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Demo checkout completed successfully.</div>}{message && <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">{message}</div>}{error && <div className="mt-4 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}<div className="mt-4 text-xs text-slate-500">Health endpoint available at <code>{landing.healthUrl}</code></div><a href={`/${companyPrefix}/orient/unsubscribe`} className="mt-4 inline-flex text-xs text-slate-500 underline-offset-4 hover:underline">Unsubscribe or manage email preferences</a></section></div></main></div>;
}
