import type { CreateConfigValues } from "@paperclipai/adapter-utils";

export interface AgentTemplate {
  id: string;
  name: string;
  role: string;
  title: string;
  icon: string;
  description: string;
  capabilities: string;
  config: Partial<CreateConfigValues>;
}

export const agentTemplates: AgentTemplate[] = [
  {
    id: "ceo",
    name: "CEO",
    role: "ceo",
    title: "Chief Executive Officer",
    icon: "crown",
    description: "Sets company vision, breaks down goals, hires and delegates to the team.",
    capabilities: "Strategic planning, goal decomposition, agent hiring, task delegation, budget oversight, cross-team coordination",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "cto",
    name: "CTO",
    role: "cto",
    title: "Chief Technology Officer",
    icon: "cpu",
    description: "Owns technical architecture, roadmap, and engineering execution.",
    capabilities: "Technical architecture, engineering roadmap, code review, technical hiring, infrastructure decisions, system design",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 1800,
    },
  },
  {
    id: "engineer",
    name: "Engineer",
    role: "engineer",
    title: "Software Engineer",
    icon: "hammer",
    description: "Writes code, builds features, fixes bugs, writes tests.",
    capabilities: "Full-stack software engineering: writes code, builds features, fixes bugs, writes tests, debugs issues, ships production-quality software",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "frontend-engineer",
    name: "Frontend Engineer",
    role: "engineer",
    title: "Frontend Engineer",
    icon: "sparkles",
    description: "Builds UI components, pages, and user-facing features.",
    capabilities: "Frontend development: React, CSS, responsive design, component architecture, accessibility, UI/UX implementation",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "backend-engineer",
    name: "Backend Engineer",
    role: "engineer",
    title: "Backend Engineer",
    icon: "database",
    description: "Builds APIs, database schemas, and server-side logic.",
    capabilities: "Backend development: APIs, database design, server architecture, performance optimization, security, data modeling",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "pm",
    name: "Product Manager",
    role: "pm",
    title: "Product Manager",
    icon: "target",
    description: "Defines product requirements, prioritizes backlog, coordinates delivery.",
    capabilities: "Product strategy, requirements gathering, backlog prioritization, user story writing, sprint planning, stakeholder communication",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 1800,
    },
  },
  {
    id: "designer",
    name: "Designer",
    role: "designer",
    title: "Product Designer",
    icon: "wand",
    description: "Creates UI/UX designs, design systems, and visual assets.",
    capabilities: "UI/UX design, wireframing, design systems, visual design, user research, prototyping, accessibility design",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "qa",
    name: "QA Engineer",
    role: "qa",
    title: "QA Engineer",
    icon: "shield",
    description: "Tests features, writes test cases, catches bugs before release.",
    capabilities: "Test planning, test case writing, manual testing, automated testing, bug reporting, regression testing, quality assurance",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    role: "devops",
    title: "DevOps Engineer",
    icon: "circuit-board",
    description: "Manages infrastructure, CI/CD, deployments, and monitoring.",
    capabilities: "CI/CD pipelines, infrastructure as code, Docker, Kubernetes, monitoring, deployment automation, cloud infrastructure",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 80,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "researcher",
    name: "Researcher",
    role: "researcher",
    title: "Researcher",
    icon: "search",
    description: "Investigates topics, analyzes data, and produces research reports.",
    capabilities: "Research, analysis, data gathering, report writing, competitive analysis, market research, technical investigation",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "cmo",
    name: "CMO",
    role: "cmo",
    title: "Chief Marketing Officer",
    icon: "globe",
    description: "Owns marketing strategy, content, branding, and growth.",
    capabilities: "Marketing strategy, content creation, brand management, growth hacking, social media, SEO, campaign management",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
  {
    id: "cfo",
    name: "CFO",
    role: "cfo",
    title: "Chief Financial Officer",
    icon: "gem",
    description: "Manages budgets, cost tracking, financial planning, and reporting.",
    capabilities: "Financial planning, budget management, cost analysis, financial reporting, revenue tracking, resource allocation",
    config: {
      adapterType: "claude_local",
      dangerouslySkipPermissions: true,
      maxTurnsPerRun: 60,
      heartbeatEnabled: true,
      intervalSec: 3600,
    },
  },
];
